# Generated by Django 4.2.25 on 2026-03-19 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('preferred_exam_type', models.CharField(blank=True, choices=[('JSS', 'JSSCE (Junior Secondary)'), ('WASSCE', 'WAEC/NECO (Senior Secondary)'), ('UTME', 'UTME/JAMB (University Entrance)'), ('POST_UTME', 'Post-UTME (University Screening)'), ('INTERVIEW', 'Interview Practice')], max_length=20)),
                ('interest_area', models.CharField(choices=[('ACADEMIC', 'Academic Exams'), ('INTERVIEW', 'Job Interviews'), ('BOTH', 'Both')], default='ACADEMIC', max_length=20)),
                ('total_practices', models.PositiveIntegerField(default=0)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_expiry', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('PRACTICE_START', 'Started Practice'), ('PRACTICE_COMPLETE', 'Completed Practice'), ('UPGRADE', 'Upgraded to Premium'), ('BOOKMARK', 'Bookmarked Question'), ('SHARE', 'Shared Result')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('JSS', 'JSSCE (Junior Secondary)'), ('WASSCE', 'WAEC/NECO (Senior Secondary)'), ('UTME', 'UTME/JAMB (University Entrance)'), ('POST_UTME', 'Post-UTME (University Screening)'), ('INTERVIEW', 'Interview Practice')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('best_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Exam Progress',
                'unique_together': {('user', 'exam_type', 'subject')},
            },
        ),
    ]
