# Generated by Django 4.2.25 on 2026-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_useractivity_userexamprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
