# Generated by Django 4.2.25 on 2026-07-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='users_email_user_id_e2d0fe_idx',
            old_name='users_email_user_id_9b0e4d_idx',
        ),
    ]
