# Generated by Django 4.2.25 on 2026-03-19 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JSS', 'JSSCE'), ('WASSCE', 'WAEC/NECO'), ('UTME', 'UTME/JAMB'), ('POST_UTME', 'Post-UTME')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-book', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='exams.examcategory')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('year', 'exam_category')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('OBJECTIVE', 'Objective (Multiple Choice)'), ('THEORY', 'Theory')], default='OBJECTIVE', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Time limit for this question in seconds (for theory/time-based questions)', null=True)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('option_e', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10)),
                ('model_answer', models.TextField(blank=True, help_text='Model answer for theory questions')),
                ('marking_guide', models.TextField(blank=True, help_text='Guide for marking theory questions')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer')),
                ('reference', models.CharField(blank=True, help_text='Reference source', max_length=255)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('question_audio', models.FileField(blank=True, null=True, upload_to='questions/audio/')),
                ('is_published', models.BooleanField(default=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this question has been used in exams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examcategory')),
                ('exam_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.examyear')),
            ],
            options={
                'ordering': ['subject', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-calculator', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_categories', models.ManyToManyField(related_name='subjects', to='exams.examcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration for full exam mode')),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('pass_mark', models.PositiveIntegerField(default=50, help_text='Minimum marks to pass')),
                ('is_free', models.BooleanField(default=True, help_text='Is this question bank free or paid?')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_trial_questions', models.PositiveIntegerField(default=5, help_text='Number of free questions available')),
                ('has_free_trial', models.BooleanField(default=True, help_text='Whether this bank offers free trial questions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='exams.examcategory')),
                ('exam_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examyear')),
                ('questions', models.ManyToManyField(related_name='question_banks', to='exams.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='exams.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.subject'),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('PRACTICE', 'Practice Mode'), ('EXAM', 'Exam Mode'), ('TIMED', 'Timed Practice')], default='PRACTICE', max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('show_explanation_on_wrong', models.BooleanField(default=True, help_text='Show explanation when answer is wrong')),
                ('allow_review', models.BooleanField(default=True, help_text='Allow reviewing questions after answering')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('answered_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage', models.FloatField(default=0.0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('questions_order', models.JSONField(blank=True, default=list, help_text='Ordered list of question IDs')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.questionbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('subject_scores', models.JSONField(blank=True, default=dict)),
                ('topic_performance', models.JSONField(blank=True, default=dict)),
                ('time_taken', models.CharField(blank=True, max_length=50)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result', to='exams.practicesession')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='exams.questionbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question_bank')},
            },
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_practices', models.PositiveIntegerField(default=0)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('weakest_topics', models.JSONField(blank=True, default=list)),
                ('strongest_topics', models.JSONField(blank=True, default=list)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examcategory')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-average_score'],
                'unique_together': {('user', 'subject', 'exam_category')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback_shown', models.BooleanField(default=False, help_text='Whether feedback was shown to user')),
                ('feedback_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.practicesession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='FreeTrialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('last_answered_date', models.DateTimeField(auto_now=True)),
                ('has_upgraded', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_trial_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='exams.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
