# Generated by Django 4.2.25 on 2026-06-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
