# Generated by Django 4.2.25 on 2026-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_useranswer_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcategory',
            name='name',
            field=models.CharField(choices=[('JSS', 'JSSCE'), ('WASSCE', 'WAEC/NECO'), ('UTME', 'UTME/JAMB'), ('POST_UTME', 'Post-UTME'), ('POST_UTME', 'Post-UTME'), ('APTITUDE', 'Aptitude Tests'), ('PROMOTION', 'Promotion Exams'), ('CIVIL', 'Civil Service Exams')], max_length=50, unique=True),
        ),
    ]
