# Generated by Django 4.2.25 on 2026-06-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_alter_examcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Main study content')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topics with descriptions and key points')),
                ('formulas', models.JSONField(blank=True, default=list, help_text='List of important formulas')),
                ('references', models.JSONField(blank=True, default=list, help_text='Recommended reference materials')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_study_notes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='exams.subject')),
            ],
            options={
                'verbose_name_plural': 'Study Notes',
                'ordering': ['subject', 'title'],
                'unique_together': {('subject', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PastQuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., WAEC Mathematics 2020', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_question_collections', to='exams.examcategory')),
                ('exam_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examyear')),
                ('questions', models.ManyToManyField(related_name='past_question_collections', to='exams.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_question_collections', to='exams.subject')),
            ],
            options={
                'ordering': ['-exam_year__year', 'subject'],
                'unique_together': {('subject', 'exam_category', 'exam_year')},
            },
        ),
    ]
