# Generated by Django 4.2.25 on 2026-10-01 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0005_question_diagram_essay"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeQuestion",
            fields=[],
            options={
                "verbose_name": "Practice Question",
                "verbose_name_plural": "Practice Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exams.question",),
        ),
        migrations.AddField(
            model_name="question",
            name="usage",
            field=models.CharField(
                choices=[
                    ("BOTH", "Practice & Main Exam"),
                    ("PRACTICE", "Practice only"),
                    ("EXAM", "Main Exam only"),
                ],
                db_index=True,
                default="BOTH",
                help_text="Practice questions are free for signed-up students; Main Exam questions power the timed (paid) exam mode.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="bank_type",
            field=models.CharField(
                choices=[("EXAM", "Main Exam"), ("PRACTICE", "Practice")],
                db_index=True,
                default="EXAM",
                help_text="Practice banks are created automatically by the Practice Portal.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="is_auto_generated",
            field=models.BooleanField(
                default=False,
                help_text="Created by the Practice Portal / Main Exam engine. Hidden from the regular question-bank listings.",
            ),
        ),
        migrations.CreateModel(
            name="PracticeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_categories",
                        to="exams.examcategory",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_categories",
                        to="exams.subject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Practice Categories",
                "ordering": ["exam_category__order", "subject__name", "order", "name"],
                "unique_together": {("exam_category", "subject", "name")},
            },
        ),
        migrations.CreateModel(
            name="ExamSyllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "edition",
                    models.CharField(
                        blank=True, help_text="e.g. 2025/2026", max_length=50
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF, Word (.docx), Markdown or text file.",
                        null=True,
                        storage=exams.models.syllabus_storage,
                        upload_to="syllabuses/",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Markdown shown on the site. Filled automatically when a .docx/.md/.txt file is uploaded.",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to the official syllabus page.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabuses",
                        to="exams.examcategory",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a general syllabus covering the whole exam body.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabuses",
                        to="exams.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_syllabuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Syllabus",
                "verbose_name_plural": "Exam Syllabuses",
                "ordering": ["exam_category__order", "order", "subject__name", "title"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="practice_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional practice set / topic this question belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="exams.practicecategory",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="practice_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banks",
                to="exams.practicecategory",
            ),
        ),
    ]
