# Generated by Django 4.2.25 on 2026-10-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_practice_portal_syllabus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["subject", "id"],
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
            },
        ),
    ]
